### ISSUE TITLE
Nome applicazione

### ISSUE THREAD

**Issue by Flavio-96** [EMAD-2019-Accenture/EMAD2019_Smart-Cart#19]
Bisognerebbe scegliere il nome dell'applicazione in maniera tale che si capisca immediatamente lo scopo e che sia un nome facile da ricordare e di impatto.

Qui sotto se ci vengono idee possiamo anche fare delle proposte e poi valutarle nel tempo.

**Comment by Flavio-96** [comment]
Proposte:

1. **Smart Cart**.

**Comment by ClaGordo** [comment]
Provo a dare un suggerimento: ShopBoost che indica un potenziamento della spesa, oppure una cosa similare.

**Comment by ClaGordo** [comment]
Oppure Smart Shop, o Smart Shopper

**Comment by Flavio-96** [comment]
> Proposte:
> 
>     1. **Smart Cart**
> 
>     2. **ShopBoost**
> 
>     3. **Smart Shop** / **Smart Shopper**

@ClaGordo ho editato il commento, aggiungo la le proposte così martedì ne discutiamo insieme nella call.
I nomi che hai proposto mi sembrano migliori del mio comunque ahah :smile:
