### ISSUE TITLE
Raffinamento UI: Completare con login, visualizzazione carrello vuoto e scegliere eventuali cambiamenti sulla visualizzazione delle raccomandazioni

### ISSUE THREAD

**Issue by emaiannone** [EMAD-2019-Accenture/EMAD2019_Smart-Cart#35]
Aggiustare alcuni elementi di interfaccia prima della demo

**Comment by Flavio-96** [comment]
Cambiato la milestone dell'issue, dopo la presentazione intermedia dell'11/11/19 vediamo un po come meglio presentare queste nuove funzionalità stabilite.
Adesso è meglio concentrarsi su una efficace presentazione dei prodotti, delle info vedendo anche se il DB oracle che ci hanno fornito ha effettivamente delle API Rest con le quali possiamo interfacciarci al DB
