### ISSUE TITLE
Modificare view raccomandazioni?

### ISSUE THREAD

**Issue by emaiannone** [EMAD-2019-Accenture/EMAD2019_Smart-Cart#36]
Le proposte sono le seguenti:

- Slider di raccomandazione nella view del prodotto singolo
- Slider per raccomandazione dei soli prodotti nel carrello nella view del carrello
- La view delle raccomandazioni sono a livello di utente, a seconda del suo profilo

**Comment by Flavio-96** [comment]
Cambiato la milestone dell'issue, dopo la presentazione intermedia dell'11/11/19 vediamo un po come meglio presentare queste nuove funzionalità stabilite.
Adesso è meglio concentrarsi su una efficace presentazione dei prodotti, delle info vedendo anche se il DB oracle che ci hanno fornito ha effettivamente delle API Rest con le quali possiamo interfacciarci al DB
