### ISSUE TITLE
Funzionalità: raccomandazioni prodotti SERVER

### ISSUE THREAD

**Issue by emaiannone** [EMAD-2019-Accenture/EMAD2019_Smart-Cart#47]
Creare un servizio ad hoc che il client interrogherà periodicamente per ricevere le raccomandazioni. Il servizio riceverà ID e stato del carrello.

- Usare filtri preferenze utente
- Tenere conto se il prodotto è già presente nel carrello
- Rispondere il prodotto migliore

- [x] Servizio Fake
- [ ] Servizio funzionante

**Comment by Flavio-96** [comment]
- Utilizzo di Apache Mahout
- Gestione logica raccomandazione: 

1. Filtro allergeni
2. Raccomandazione pesata in base a profilo utente
